#!/usr/bin/env ruby

require File.dirname(__FILE__) + '/script'

# This is intended to be ran as part of Vagrant provisioning.
# It will use the Script class (in script.rb)
# to execute the scripts below both in parallel and sequence depending
# on the scripts importance to the following ones.
# 
# The end result should configure a Vagrant instance with a 
# fully functional DocumentCloud server
#
# The scripts are located in the scripts directory, and can be re-ran if needed
# from there.  We've attempted to make them as re-entrant as possible
# but they may not be fully there yet.
#


ENV['RAILS_ENV'] = 'development'
LOGIN            = 'test@example.com'
PASSWORD         = 'documentcloud'
Script.user      = ENV['USERNAME'] = 'ubuntu'
Script.directory = '/vagrant/scripts'
REPOSITORY       = 'https://github.com/documentcloud/documentcloud.git'

Script[ :update               ].run_weekly :as_root=>true, :wait=>true, :msg=>'Will take >10 minutes'
Script[ :install_dependencies ].run_once   :as_root=>true, :wait=>true, :msg=>'Will take >5 minutes'

Script[ :speed_up_ssh         ].run_once   :as_root=>true
Script[ :pretty_motd          ].run_once   :as_root=>true
Script[ :github_keys          ].run_once
Script[ :copy_secrets         ].run_once

Script.wait_for_completion

unless File.directory?( 'documentcloud' )
  Script.output do
    STDERR.puts "documentcloud directory doesn't exist."
    STDERR.puts "Checking it out from #{REPOSITORY}"
    Script[:clone_documentcloud].run :wait=>true, :args=>{:repo=>REPOSITORY}
  end
end

Script[:install_gems         ].run_once :wait=>true
Script[:install_nginx        ].run_once :wait=>true, :as_root=>true

Script[:configure_nginx      ].run_once :as_root=>true,:shell=>'/usr/bin/ruby'
Script[:configure_postgresql ].run_once :as_root=>true

Script.wait_for_completion

Script[:provision           ].run_once :shell=>'/usr/bin/ruby', :wait=>true, :args=>{ :login=> LOGIN, :password=>PASSWORD } 
Script[:start_up_everything ].run
Script.wait_for_completion

ip = `/sbin/ifconfig eth1 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'`

Script.output do
  puts <<-EOS
####################################################################
#  All Done.
#  A fully configured DocumentCloud should be running on vagrant at
#     http://#{ip}
#  Log in as: #{LOGIN} with password: #{PASS}
####################################################################
EOS
end
